builds:
  - main: ./cmd/steerer
    binary: steerer
    ldflags: -s -w -X github.com/stefanprodan/steerer/pkg/version.REVISION={{.Commit}}
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
archive:
  name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  files:
  - none*
