sudo: required
language: go

go:
- 1.10.x

services:
- docker

addons:
  apt:
    packages:
    - docker-ce

script:
- set -e
- make test
- make verify-codegen
- make build

after_success:
- if [ -z "$DOCKER_USER" ]; then
    echo "PR build, skipping Docker Hub push";
  else
    docker tag stefanprodan/steerer:latest stefanprodan/steerer:${TRAVIS_COMMIT};
    echo $DOCKER_PASS | docker login -u=$DOCKER_USER --password-stdin;
    docker push stefanprodan/steerer:${TRAVIS_COMMIT};
  fi
- if [ -z "$TRAVIS_TAG" ]; then
    echo "Not a release, skipping Docker Hub push";
  else
    docker tag stefanprodan/steerer:latest stefanprodan/steerer:$TRAVIS_TAG;
    echo $DOCKER_PASS | docker login -u=$DOCKER_USER --password-stdin;
    docker push stefanprodan/steerer:latest;
    docker push stefanprodan/steerer:$TRAVIS_TAG;
  fi

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL http://git.io/goreleaser | bash
  on:
    tags: true
