sudo: required
language: go

branches:
  except:
    - /gh-pages.*/
    - /docs-.*/

go:
- 1.12.x

services:
- docker

addons:
  apt:
    packages:
    - docker-ce

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL http://git.io/goreleaser | bash
  on:
    tags: true
