apiVersion: steerer.app/v1beta1
kind: Canary
metadata:
  name: podinfoc
  namespace: test
spec:
  targetKind: Deployment
  virtualService:
    name: podinfoc
  primary:
    name: podinfoc-primary
    host: podinfoc-primary
  canary:
    name: podinfoc-canary
    host: podinfoc-canary
  canaryAnalysis:
    # max number of failed metric checks
    # before rolling back the canary
    threshold: 10
    # max traffic percentage routed to canary
    # percentage (0-100)
    maxWeight: 50
    # canary increment step
    # percentage (0-100)
    stepWeight: 10
    metrics:
    - name: istio_requests_total
      # minimum req success rate (non 5xx responses)
      # percentage (0-100)
      threshold: 99
      interval: 1m
    - name: istio_request_duration_seconds_bucket
      # maximum req duration P99
      # milliseconds
      threshold: 500
      interval: 30s
