apiVersion: v1
kind: Service
metadata:
  name: flagger-helmtester
  labels:
    app: flagger-helmtester
spec:
  type: ClusterIP
  selector:
    app: flagger-helmtester
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http