version: 2.1
jobs:

  build-binary:
    docker:
      - image: circleci/golang:1.12
    working_directory: ~/build
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}
      - run: |
          CGO_ENABLED=0 GOOS=linux go build \
              -ldflags "-s -w -X github.com/weaveworks/flagger/pkg/version.REVISION=${CIRCLE_SHA1}" \
              -a -installsuffix cgo -o flagger ./cmd/flagger/*
          ./flagger -version
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod/"
      - run: |
          mkdir workspace
          cp flagger workspace/flagger
      - persist_to_workspace:
          root: workspace
          paths:
            - flagger

  build-container:
    docker:
      - image: circleci/golang:1.12
    working_directory: /build
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: /tmp/workspace
      - run: |
          cp /tmp/workspace/flagger .
          chmod +x flagger
          docker build -t weaveworks/flagger:${CIRCLE_SHA1} . -f ./test/Dockerfile.ci

  e2e-istio-testing:
    machine: true
    steps:
      - checkout
      - run: test/e2e-kind.sh
      - run: test/e2e-istio.sh
      - run: test/e2e-istio-build.sh
      - run: test/e2e-tests.sh

  e2e-smi-istio-testing:
    machine: true
    steps:
      - checkout
      - run: test/e2e-kind.sh
      - run: test/e2e-istio.sh
      - run: test/e2e-smi-istio-build.sh
      - run: test/e2e-tests.sh canary

  e2e-supergloo-testing:
    machine: true
    steps:
      - checkout
      - run: test/e2e-kind.sh
      - run: test/e2e-supergloo.sh
      - run: test/e2e-build.sh supergloo:test.supergloo-system
      - run: test/e2e-tests.sh canary

  e2e-gloo-testing:
    machine: true
    steps:
      - checkout
      - run: test/e2e-kind.sh
      - run: test/e2e-gloo.sh
      - run: test/e2e-gloo-build.sh
      - run: test/e2e-gloo-tests.sh

  e2e-nginx-testing:
    machine: true
    steps:
      - checkout
      - run: test/e2e-kind.sh
      - run: test/e2e-nginx.sh
      - run: test/e2e-nginx-build.sh
      - run: test/e2e-nginx-tests.sh

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-binary
      - build-container:
          requires:
            - build-binary
          filters:
            branches:
              ignore:
                - /gh-pages.*/
                - /docs-.*/
                - /release-.*/

#      - e2e-istio-testing:
#          filters:
#            branches:
#              ignore:
#                - /gh-pages.*/
#                - /docs-.*/
#                - /release-.*/
#      - e2e-smi-istio-testing:
#          filters:
#            branches:
#              ignore:
#                - /gh-pages.*/
#                - /docs-.*/
#                - /release-.*/
#      - e2e-supergloo-testing:
#          filters:
#            branches:
#              ignore:
#                - /gh-pages.*/
#                - /docs-.*/
#                - /release-.*/
#      - e2e-nginx-testing:
#          filters:
#            branches:
#              ignore:
#                - /gh-pages.*/
#                - /docs-.*/
#                - /release-.*/
#      - e2e-gloo-testing:
#          filters:
#            branches:
#              ignore:
#                - /gh-pages.*/
#                - /docs-.*/
#                - /release-.*/