ersion: 2.1
jobs:
  website:
    docker:
      - image: circleci/node:12.8
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Build website
          command: |
            yarn docs:build
            mkdir $HOME/site
            sudo apt-get update && sudo apt-get install rsync
            rsync -avzh docs/.vuepress/dist/ $HOME/site
      - run:
          name: Publish website
          command: |
            if [[ $GITHUB_TOKEN ]]; then
              REPOSITORY="https://weaveworksbot:${GITHUB_TOKEN}@github.com/weaveworks/flagger.git"
              git config user.email weaveworksbot@users.noreply.github.com
              git config user.name weaveworksbot
              git remote set-url origin ${REPOSITORY}
              git checkout gh-pages
              rm -rf assets
              rsync -avzh $HOME/site/ .
              rm -rf node_modules
              git add .
              git commit -m "Publish website"
              git push origin gh-pages
            else
              echo "No GitHub token found! Skip publishing"
            fi

workflows:
  version: 2
  publish-website:
    jobs:
      - website
