version: 2.1
jobs:
  e2e-testing:
    machine: true
    steps:
      - checkout
      - run: test/e2e-prerequisites.sh
      - run: test/e2e-kind.sh

workflows:
  version: 2
  build-and-test:
    jobs:
      - e2e-testing
