version: 2.1
jobs:
  e2e-istio-testing:
    machine: true
    steps:
      - checkout
      - run: test/e2e-kind.sh
      - run: test/e2e-istio.sh
      - run: test/e2e-build.sh
      - run: test/e2e-tests.sh

  e2e-supergloo-testing:
    machine: true
    steps:
      - checkout
      - run: test/e2e-kind.sh
      - run: test/e2e-supergloo.sh
      - run: test/e2e-build.sh supergloo:test.supergloo-system
      - run: test/e2e-tests.sh canary

  e2e-gloo-testing:
    machine: true
    steps:
      - checkout
      - run: test/e2e-kind.sh
      - run: test/e2e-gloo.sh
      - run: test/e2e-gloo-build.sh
      - run: test/e2e-gloo-tests.sh

  e2e-nginx-testing:
    machine: true
    steps:
      - checkout
      - run: test/e2e-kind.sh
      - run: test/e2e-nginx.sh
      - run: test/e2e-nginx-build.sh
      - run: test/e2e-nginx-tests.sh

workflows:
  version: 2
  build-and-test:
    jobs:
      - e2e-istio-testing:
          filters:
            branches:
              ignore:
                - /gh-pages.*/
                - /docs-.*/
                - /release-.*/
      - e2e-supergloo-testing:
          filters:
            branches:
              ignore:
                - /gh-pages.*/
                - /docs-.*/
                - /release-.*/
      - e2e-nginx-testing:
          filters:
            branches:
              ignore:
                - /gh-pages.*/
                - /docs-.*/
                - /release-.*/
      - e2e-gloo-testing:
          filters:
            branches:
              ignore:
                - /gh-pages.*/
                - /docs-.*/
                - /release-.*/