version: 2.1
jobs:
  build:
    machine: true
    steps:
      - run: "echo skip"

workflows:
  version: 2
  build:
    jobs:
      - build:
          branches:
            ignore:
              - gh-pages
