apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: podinfo
  namespace: test
spec:
  gateways:
  - public-gateway.istio-system.svc.cluster.local
  - mesh
  hosts:
  - app.istio.weavedx.com
  - podinfo
  http:
  - match:
    - headers:
        user-agent:
          regex: ^(?!.*Chrome)(?=.*\bSafari\b).*$
      uri:
        prefix: "/version/"
    rewrite:
      uri: /api/info
    route:
    - destination:
        host: podinfo-primary
        port:
          number: 9898
      weight: 0
    - destination:
        host: podinfo
        port:
          number: 9898
      weight: 100
  - match:
      - uri:
          prefix: "/version/"
    rewrite:
      uri: /api/info
    route:
    - destination:
        host: podinfo-primary
        port:
          number: 9898
      weight: 100
