apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: canaries.flagger.app
spec:
  group: flagger.app
  version: v1beta1
  versions:
    - name: v1beta1
      served: true
      storage: true
  names:
    plural: canaries
    singular: canary
    kind: Canary
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required:
            - targetKind
            - virtualService
            - primary
            - canary
            - canaryAnalysis
          properties:
            targetKind:
              type: string
            virtualService:
              properties:
                name:
                  type: string
            primary:
              properties:
                name:
                  type: string
                host:
                  type: string
            canary:
              properties:
                name:
                  type: string
                host:
                  type: string
            canaryAnalysis:
              properties:
                threshold:
                  type: number
                maxWeight:
                  type: number
                stepWeight:
                  type: number
                metrics:
                  type: array
                  properties:
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        interval:
                          type: string
                          pattern: "^[0-9]+(m)"
                        threshold:
                          type: number

