apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "steerer.name" . }}
  labels:
    app: {{ template "steerer.name" . }}
    chart: {{ template "steerer.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
