apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  annotations:
    apps.weave.works/canary-revision: ""
    apps.weave.works/canary-status: ""
  labels:
    app: podinfo
  name: podinfo
  namespace: test
spec:
  gateways:
  - public-gateway.istio-system.svc.cluster.local
  hosts:
  - app.istio.weavedx.com
  - podinfo
  http:
  - route:
    - destination:
        host: podinfo
        port:
          number: 9898
      weight: 100
    - destination:
        host: podinfo-canary
        port:
          number: 9898
      weight: 0
    timeout: 30s
