apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: podinfo
  namespace: test
  labels:
    app: podinfo
spec:
  gateways:
  - mesh
  - public-gateway.istio-system.svc.cluster.local
  hosts:
  - podinfo
  - app.istio.weavedx.com
  http:
  - route:
    - destination:
        host: podinfo-primary
      weight: 50
    - destination:
        host: podinfo-canary
      weight: 50
    timeout: 5s
