apiVersion: v1
kind: Secret
metadata:
  name: podinfo-secret-env
  namespace: test
data:
  password: cGFzc3dvcmQ=
  user: YWRtaW4=
---
apiVersion: v1
kind: Secret
metadata:
  name: podinfo-secret-vol
  namespace: test
data:
  key: cGFzc3dvcmQ=
