apiVersion: v1
kind: Service
metadata:
  name: {{ template "podinfo-flagger.primary" . }}
  labels:
    app: {{ template "podinfo-flagger.fullname" . }}
    chart: {{ template "podinfo-flagger.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.containerPort }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ template "podinfo-flagger.primary" . }}
