name: e2e

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  kind:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        provider:
          - istio
          - linkerd
          - contour
          - nginx
          - traefik
          - gloo
          - skipper
          - kubernetes
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Kubernetes
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.10.0"
          image: kindest/node:v1.20.2@sha256:8f7ea6e7642c0da54f04a7ee10431549c0257315b3a634f6ef2fecaaedb19bab
      - name: Build container image
        run: |
          docker build -t test/flagger:latest .
          kind load docker-image test/flagger:latest
      - name: Run tests
        run: |
          ./test/${{ matrix['provider'] }}/run.sh
