apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "podinfo-steerer.canary" . }}
  labels:
    app: {{ template "podinfo-steerer.fullname" . }}
    chart: {{ template "podinfo-steerer.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ template "podinfo-steerer.canary" . }}
  template:
    metadata:
      labels:
        app: {{ template "podinfo-steerer.canary" . }}
      annotations:
        prometheus.io/scrape: "true"
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: podinfod
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command:
            - ./podinfo
            - --port={{ .Values.containerPort }}
            - --level={{ .Values.logLevel }}
          env:
          - name: PODINFO_UI_COLOR
            value: green
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - podcli
              - check
              - http
              - localhost:{{ .Values.containerPort }}/healthz
          readinessProbe:
            exec:
              command:
              - podcli
              - check
              - http
              - localhost:{{ .Values.containerPort }}/readyz
            periodSeconds: 3
          volumeMounts:
          - name: data
            mountPath: /data
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
      - name: data
        emptyDir: {}
