apiVersion: v1
kind: Service
metadata:
  name: {{ template "podinfo-steerer.canary" . }}
  labels:
    app: {{ template "podinfo-steerer.fullname" . }}
    chart: {{ template "podinfo-steerer.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.containerPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "podinfo-steerer.canary" . }}
